const grid = document.getElementById('grid'); const empty = document.getElementById('empty'); const modal = document.getElementById('modal'); const form = document.getElementById('shortcutForm'); const nameInput = document.getElementById('nameInput'); const pathInput = document.getElementById('pathInput'); const iconInput = document.getElementById('iconInput'); const countLabel = document.getElementById('countLabel'); const status = document.getElementById('status'); let shortcuts = [];
const save = async () => { await window.fastAccses.save(shortcuts); status.textContent = 'All changes saved'; };
function render(){ grid.innerHTML=''; empty.style.display=shortcuts.length?'none':'block'; countLabel.textContent=`${shortcuts.length} item${shortcuts.length===1?'':'s'} saved locally`; shortcuts.forEach((item,index)=>{ const card=document.createElement('article'); card.className='card'; card.innerHTML=`<div class="card-top"><div class="shortcut-icon">${item.icon||'⚡'}</div><button class="more" title="Remove">⋯</button></div><h4>${escapeHtml(item.name)}</h4><div class="path" title="${escapeHtml(item.path)}">${escapeHtml(item.path)}</div><button class="launch">Launch</button>`; card.querySelector('.launch').onclick=()=>launch(item); card.querySelector('.more').onclick=async()=>{if(confirm(`Remove “${item.name}”?`)){shortcuts.splice(index,1);await save();render()}}; grid.appendChild(card); }); }
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function launch(item){const result=await window.fastAccses.execute(item.path); if(!result.ok) alert(`Could not launch this path.\n\n${result.error||'Please check that it exists.'}`);}
function openModal(){form.reset();iconInput.value='⚡';modal.showModal();nameInput.focus();}
document.getElementById('addBtn').onclick=openModal; document.getElementById('emptyAddBtn').onclick=openModal;
document.getElementById('clearBtn').onclick=async()=>{if(shortcuts.length&&confirm('Remove all shortcuts?')){shortcuts=[];await save();render()}};
document.getElementById('fileBtn').onclick=async()=>{const p=await window.fastAccses.choosePath('file');if(p)pathInput.value=p}; document.getElementById('folderBtn').onclick=async()=>{const p=await window.fastAccses.choosePath('folder');if(p)pathInput.value=p};
form.addEventListener('submit',async e=>{e.preventDefault(); shortcuts.push({name:nameInput.value.trim(),path:pathInput.value.trim(),icon:iconInput.value.trim()||'⚡'}); await save(); render(); modal.close();});
(async()=>{shortcuts=await window.fastAccses.list();render()})();
