const grid = document.getElementById('grid'); const empty = document.getElementById('empty'); const modal = document.getElementById('modal'); const form = document.getElementById('shortcutForm'); const nameInput = document.getElementById('nameInput'); const pathInput = document.getElementById('pathInput'); const iconInput = document.getElementById('iconInput'); const iconPicker = document.getElementById('iconPicker'); const countLabel = document.getElementById('countLabel'); const status = document.getElementById('status'); let shortcuts = [];
const icons = ['fa-bolt','fa-rocket','fa-folder','fa-file','fa-gears','fa-code','fa-terminal','fa-globe','fa-music','fa-image','fa-video','fa-gamepad','fa-briefcase','fa-house','fa-star','fa-heart','fa-download','fa-cloud','fa-lock','fa-wand-magic-sparkles'];
function iconMarkup(icon){ return String(icon||'fa-solid fa-bolt').startsWith('fa-') ? `<i class="${escapeHtml(icon)}"></i>` : escapeHtml(icon||'⚡'); }
function initIconPicker(){ iconPicker.innerHTML=icons.map(name=>`<button type="button" class="icon-choice" data-icon="fa-solid ${name}" title="${name}"><i class="fa-solid ${name}"></i></button>`).join(''); iconPicker.onclick=e=>{const choice=e.target.closest('.icon-choice');if(!choice)return;iconInput.value=choice.dataset.icon;document.querySelectorAll('.icon-choice').forEach(b=>b.classList.remove('selected'));choice.classList.add('selected')}; }
const save = async () => { await window.fastAccses.save(shortcuts); status.textContent = 'All changes saved'; };
function render(){ grid.innerHTML=''; empty.style.display=shortcuts.length?'none':'block'; countLabel.textContent=`${shortcuts.length} item${shortcuts.length===1?'':'s'} saved locally`; shortcuts.forEach((item,index)=>{ const card=document.createElement('article'); card.className='card'; card.innerHTML=`<div class="card-top"><div class="shortcut-icon">${iconMarkup(item.icon)}</div><button class="more" title="Remove">⋯</button></div><h4>${escapeHtml(item.name)}</h4><div class="path" title="${escapeHtml(item.path)}">${escapeHtml(item.path)}</div><button class="launch">Launch</button>`; card.querySelector('.launch').onclick=()=>launch(item); card.querySelector('.more').onclick=async()=>{if(confirm(`Remove “${item.name}”?`)){shortcuts.splice(index,1);await save();render()}}; grid.appendChild(card); }); }
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function launch(item){const result=await window.fastAccses.execute(item.path); if(!result.ok) alert(`Could not launch this path.\n\n${result.error||'Please check that it exists.'}`);}
function openModal(){form.reset();iconInput.value='fa-solid fa-bolt';document.querySelectorAll('.icon-choice').forEach(b=>b.classList.toggle('selected',b.dataset.icon===iconInput.value));modal.showModal();nameInput.focus();}
document.getElementById('addBtn').onclick=openModal; document.getElementById('emptyAddBtn').onclick=openModal;
document.getElementById('clearBtn').onclick=async()=>{if(shortcuts.length&&confirm('Remove all shortcuts?')){shortcuts=[];await save();render()}};
document.getElementById('fileBtn').onclick=async()=>{const p=await window.fastAccses.choosePath('file');if(p)pathInput.value=p}; document.getElementById('folderBtn').onclick=async()=>{const p=await window.fastAccses.choosePath('folder');if(p)pathInput.value=p};
form.addEventListener('submit',async e=>{e.preventDefault(); shortcuts.push({name:nameInput.value.trim(),path:pathInput.value.trim(),icon:iconInput.value.trim()||'⚡'}); await save(); render(); modal.close();});
(async()=>{initIconPicker();shortcuts=await window.fastAccses.list();render()})();
